# Generated by Django 6.0.3 on 2026-04-15 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="total_score",
        ),
    ]
