# Generated by Django 6.0.3 on 2026-04-16 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0002_remove_round_total_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="location",
            field=models.CharField(default="Marion, MA", max_length=100),
        ),
        migrations.CreateModel(
            name="TeeSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        help_text="e.g., Blue, White, Gold, Black, or Combo",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="USGA Course Rating (e.g., 71.2)",
                        max_digits=4,
                    ),
                ),
                (
                    "slope",
                    models.IntegerField(help_text="USGA Slope Rating (usually 55-155)"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tees",
                        to="scoring.course",
                    ),
                ),
            ],
        ),
    ]
