# Generated by Django 6.0.3 on 2026-04-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0003_alter_course_location_teeset"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="differential",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=5
            ),
            preserve_default=False,
        ),
    ]
