# Generated by Django 6.0.3 on 2026-04-16 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0004_round_differential"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="scores",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="round",
            name="tee_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scoring.teeset",
            ),
        ),
        migrations.AlterField(
            model_name="holescore",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hole_scores",
                to="scoring.round",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="date_played",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
