# Generated by Django 6.0.4 on 2026-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0005_round_scores_round_tee_set_alter_holescore_round_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="holes_played",
            field=models.IntegerField(
                choices=[(9, "9 Holes"), (18, "18 Holes")], default=18
            ),
        ),
    ]
