# Generated by Django 6.0.4 on 2026-04-21 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0006_round_holes_played"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hole",
            name="course",
        ),
        migrations.RemoveField(
            model_name="round",
            name="tee_set",
        ),
        migrations.AddField(
            model_name="hole",
            name="tee_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holes",
                to="scoring.teeset",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="completed_holes",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="round",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="round",
            name="external_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="total_gross_score",
            field=models.IntegerField(default=0),
        ),
    ]
