# Generated by Django 6.0.4 on 2026-04-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scoring",
            "0007_remove_hole_course_remove_round_tee_set_hole_tee_set_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="scores",
            field=models.IntegerField(default=0),
        ),
    ]
