# Generated by Django 6.0.4 on 2026-04-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0008_alter_round_scores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="date_played",
        ),
        migrations.RemoveField(
            model_name="round",
            name="holes_played",
        ),
        migrations.RemoveField(
            model_name="round",
            name="scores",
        ),
    ]
