# Generated by Django 6.0.4 on 2026-04-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0009_remove_round_date_played_remove_round_holes_played_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holescore",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="scoring.round",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="differential",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=5, null=True
            ),
        ),
    ]
