# Generated by Django 6.0.5 on 2026-05-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0010_alter_holescore_round_alter_round_differential"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="placeholder-slug"),
        ),
    ]
