# Generated by Django 6.0.5 on 2026-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0011_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
