# Generated by Django 6.0.5 on 2026-06-06 14:31

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0012_alter_course_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="round",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="round",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name="hole",
            unique_together={("tee_set", "hole_number")},
        ),
        migrations.AlterUniqueTogether(
            name="teeset",
            unique_together={("course", "name")},
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["user", "-date"], name="scoring_rou_user_id_c8056c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["course", "-date"], name="scoring_rou_course__5500a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["user", "course", "-date"],
                name="scoring_rou_user_id_7e81b7_idx",
            ),
        ),
    ]
