# Generated by Codex on 2026-07-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0013_alter_course_options_alter_round_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="tee_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rounds",
                to="scoring.teeset",
            ),
        ),
    ]
